language: python
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_script:
  - pip install -r requirements.txt
  - chmod +x manage.py

env: DJANGO_SETTINGS_MODULE="PurBeurre_django.settings"

script:
  - ./manage.py test

# ...
test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
# safelist
branches:
  only:
    - staging

# ...services:
  grafana:
    services:
  grafana:
services:
  grafana: