language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="PurBeurre_django.settings"

script:
  - ./manage.py test

# ...
test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
# safelist
branches:
  only:
    - staging

# ...