language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="PurBeurre_django.settings"

script:
  - ./manage.py test

# ...

# safelist
branches:
  only:
    - staging

# ...