# Generated by Django 2.2.2 on 2019-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='stores',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
