# Generated by Django 2.2.2 on 2019-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0004_auto_20190624_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='novascore',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
